### PR TITLE
Support index.js with single quotes

### LINKED ISSUE #100: Component generator error with single quotes string
On a project we use single quotes on js files. So our `frontend/components/index.js` has list of components with single quotes.  

The problem with when we generate a new component, the [`import_to_packs` method](https://github.com/komposable/komponent/blob/master/lib/generators/component/component_generator.rb#L37) seems to remove all components import and adding the new one.

```diff
- import "components/alert/alert";
- import "components/button/button";
- import "components/container/container";
- import "components/footer/footer";
- import "components/navigation/navigation";
- import "components/pagination/pagination";
+ import "components/test/test";
```

Not sure what could be done. May be using the `Komponent::Component.all` method a created on #95, could help us to do the import list directly by getting the list of present components.

### PR DESCRIPTION
**Pull request by Spone**
Fix #100

### CODE REVIEW

**Comment by nicolas-brousse** [comment]
Do you think it's possible to have a patch release for that?

**Comment by Spone** [comment]
@florentferry if you have time?

**Comment by florentferry** [comment]
@nicolas-brousse Yes, I can push a release on rubygems tonight.

**Comment by nicolas-brousse** [comment]
Could be nice, thanks!

**Pull request merged**
