### PR TITLE
Fix translation lookup in partials

### PR DESCRIPTION
**Pull request by stevschmid**
We noticed that the translation lookup in partials was broken. Using the helper `t('.key')` in partial `bar` within a component `foo` would lookup the key in the scope of `bar_component` instead of `foo_component`.

This PR addresses this issue. In the example above, the resulting key from the helper would be `foo_component.bar.key` 

~~**This PR is not compatible with the way komponent handles namespacing at the moment, please do not merge! Refer to #117**~~

### CODE REVIEW

**Comment by stevschmid** [comment]
I just added compatibility in 6b72af9 for the current namespacing layout (see #117). 
It seems code climate does not like my code →  "Cognitive Complexity of 6". Alas, I don't have the mental strength right now to address this too.

**Comment by Spone** [comment]
Thanks! I'll take care of refactoring to make Code Climate happy.

**Comment by Spone** [comment]
Done. Would you mind adding an item in the Changelog, and maybe describe this behavior in the Readme?

**Comment by stevschmid** [comment]
Sure thing! I just added a line to the changelog. Do you think it's necessary to explain the behavior in the README? I personally think it's quite intuitive and consistent with the "Rails way".

**Comment by Spone** [comment]
You're right, let's merge :)

**Pull request merged**
