### PR TITLE
align generated js with airbnb linter

### PR DESCRIPTION
**Pull request by andrzejsliwa**
generated code should be ready to commit, and pass linters

### CODE REVIEW

**Comment by andrzejsliwa** [comment]
@florentferry may I ask you for review

**Comment by Spone** [comment]
Yes, I totally agree, I had the same issue!

**Comment by florentferry** [comment]
Hello,

That's ok for me. Can just you provide link to rules from linter applied here, for reference purpose.

**Comment by andrzejsliwa** [comment]
@florentferry @Spone can you merge it or give me maintainer rights?

**Comment by andrzejsliwa** [comment]
@florentferry reference for me was just standard settings of linter

**Comment by andrzejsliwa** [comment]
@florentferry when you will release new version, I just found that autoloading its not working in current version but you just solve it here https://github.com/komposable/komponent/commit/f41b4f803625a8647fc5cf4443e76ef15f22266a

**Pull request merged**
