### PR TITLE
Make sure that +all+ returns namespaced components

### LINKED ISSUE #125: Add nested components support in styleguide
When we worked on the styleguide view, we did not include the nested components in the nav.

It would be great to fix that :)

### PR DESCRIPTION
**Pull request by apauly**
Fix that `Komponent::Component.all` actually returns all components, including namespaced components.

Close #125

### CODE REVIEW

**Comment by Spone** [comment]
Great! Thanks @apauly for the contribution! I guess it fixes #125 right?

**Comment by apauly** [comment]
Might be, but I'm not sure as I haven't worked with the styleguide yet.

**Comment by apauly** [comment]
Hey @nicolas-brousse , 
did you find some time already to review this? If there's anything missing please let me know.

**Comment by nicolas-brousse** [comment]
Hi @apauly! Sorry I was off the week before. I'll try to found some times in the following days.

**Comment by Spone** [comment]
Close #125

**Comment by nicolas-brousse** [comment]
@apauly Good news, I'm looking into it. Sorry for the time I took.

I'm doing some more tests locally to check some other cases.

**Comment by nicolas-brousse** [comment]
LGTM.

Before we go to merge this PR. Did you authorized maintainers to update your PR?

I did some other tests locally and I would like to push them. Otherwise I'll do it later.

I added two new components two have other path examples in the future.

**Comment by nicolas-brousse** [comment]
Thanks for your work @apauly

**Pull request merged**
